sudo: required
services:
  - docker

env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test $NPM_TARGET

after_success:
  - set -x -v;
    set -e;
    if [ "${NPM_TARGET}"= "test"]; then
      docker tag probot_hello probot-hello:$(git rev-parse HEAD);
    else
      echo "skipping docker tag";
    fi;
    docker images;
    awr +x +v;
